GET http://localhost:8080/api/v1/users

###

GET http://localhost:8080/api/v1/users/5

###

POST http://localhost:8080/api/v1/users HTTP/1.1
content-type: application/json

{
  "username": "test",
  "name": "Test",
  "email": "test@test.com",
  "password": "test"
}

###

PUT http://localhost:8080/api/v1/users/9 HTTP/1.1
content-type: application/json

{
  "username": "test",
  "name": "Test",
  "email": "test@test.com",
  "gender": "F"
}

###

DELETE http://localhost:8080/api/v1/users/10